services:
  - type: web
    name: chemnitz-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chemnitz-db
          property: connectionString
    plan: free
