# Generated by Django 5.2.1 on 2025-06-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_sites', '0002_location_note_created_at_alter_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='amenity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
