# Generated by Django 5.2.1 on 2025-06-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_sites', '0003_location_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='addr_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='addr_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
