# Generated by Django 5.2.1 on 2025-06-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_sites', '0004_location_addr_city_location_addr_street'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
